import { AppData } from './types';

export const INITIAL_DATA: AppData = {
  "projects": [
    {
      "project_code": "PRJ-01",
      "engagement_type": "Proyecto",
      "client_alias": "Atlas Foods",
      "project_name": "Global Contract Management",
      "project_type_api": "Automatizacion",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Daniel Rojas",
      "owner_role": "Commercial / Delivery",
      "start_date": null,
      "target_date": null,
      "business_value": "28000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Plataforma Integral de Gestion de Contratos para el Equipo Legal Global.",
      "recent_completed_examples": "No completed examples visible"
    },
    {
      "project_code": "PRJ-02",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Observability Hub",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Daniel Rojas",
      "owner_role": "Commercial / Delivery",
      "start_date": null,
      "target_date": null,
      "business_value": "8000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path. This service requires ongoing follow-up and periodic cleanup.",
      "summary": "Sistema de observabilidad multi-cliente (salud + adopcion).",
      "recent_completed_examples": "No completed examples visible"
    },
    {
      "project_code": "PRJ-03",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Lunara Health",
      "project_name": "Patient Care Assistant",
      "project_type_api": "Automatizacion",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Camila Torres",
      "owner_role": "Delivery",
      "start_date": "2026-03-02",
      "target_date": "2026-03-02",
      "business_value": "14000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "1",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path. This service requires ongoing follow-up and periodic cleanup.",
      "summary": "Sistema de reservas y chatbot.",
      "recent_completed_examples": "TUE-24 · Revisar outbounds | TUE-3 · Tabla de tags del bot | TUE-4 · Horarios por sedes"
    },
    {
      "project_code": "PRJ-04",
      "engagement_type": "Proyecto",
      "client_alias": "Pioneer Insurance",
      "project_name": "Quotation Engine",
      "project_type_api": "Automatizacion",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Camila Torres",
      "owner_role": "Delivery",
      "start_date": "2026-03-02",
      "target_date": "2026-03-05",
      "business_value": "25000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Automatizacion de slips de cotizacion.",
      "recent_completed_examples": "GRQ-20 · Bloqueo soft seguros | GRQ-9 · Condiciones a estructura existente | GRQ-2 · Primera version de slips"
    },
    {
      "project_code": "PRJ-05",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Orion Mobility",
      "project_name": "Multi-Brand Sales Assistant",
      "project_type_api": "Automatizacion",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Laura Gomez",
      "owner_role": "Delivery",
      "start_date": "2026-02-25",
      "target_date": "2026-03-16",
      "business_value": "3000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path. This service requires ongoing follow-up and periodic cleanup.",
      "summary": "Proyecto creado via API.",
      "recent_completed_examples": "ALC-15 · Identificar ciudad del usuario | ALC-2 · Eficiencia operativa del asesor | ALC-42 · Google Sheets Meta Leads"
    },
    {
      "project_code": "PRJ-06",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Recovery and Compensation Ops",
      "project_type_api": "Automatizacion",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Laura Gomez",
      "owner_role": "Delivery",
      "start_date": "2026-02-27",
      "target_date": "2026-03-16",
      "business_value": "30000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "1",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path. This service requires ongoing follow-up and periodic cleanup.",
      "summary": "Proyecto creado via API.",
      "recent_completed_examples": "REV-1 · Conectar Wati | REV-11 · Asociar fases del proyecto | REV-17 · Feedback pruebas produccion"
    },
    {
      "project_code": "PRJ-07",
      "engagement_type": "Proyecto",
      "client_alias": "Velora Credit",
      "project_name": "Credit Assistant",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Camila Torres",
      "owner_role": "Delivery",
      "start_date": "2026-04-08",
      "target_date": "2026-04-13",
      "business_value": null,
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto sincronizado desde la plataforma de desarrollo (SUE).",
      "recent_completed_examples": "SUE-1 · Respuesta errada | SUE-11 · Error en capacidad | SUE-12 · Error en capacidad"
    },
    {
      "project_code": "PRJ-08",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Camila Torres",
      "owner_role": "Delivery",
      "start_date": null,
      "target_date": "2026-04-27",
      "business_value": "35000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto sincronizado desde la plataforma de desarrollo (QUI).",
      "recent_completed_examples": "QUI-10 · Mapa comerciales | QUI-11 · Criterios calificacion | QUI-12 · Canal WhatsApp CO"
    },
    {
      "project_code": "PRJ-09",
      "engagement_type": "Proyecto",
      "client_alias": "Ferroline Industrial",
      "project_name": "Industrial OCR Quoter",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Camila Torres",
      "owner_role": "Delivery",
      "start_date": null,
      "target_date": "2026-05-13",
      "business_value": "22000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "1",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto sincronizado desde la plataforma de desarrollo (TMX).",
      "recent_completed_examples": "TMX-13 · Cotizador con conexion real | TMX-14 · Clave de acceso + proxy | TMX-4 · Espera integracion API"
    },
    {
      "project_code": "PRJ-10",
      "engagement_type": "Proyecto",
      "client_alias": "Pulse Creative",
      "project_name": "Commercial Image Pipeline",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Camila Torres",
      "owner_role": "Delivery",
      "start_date": null,
      "target_date": "2026-05-15",
      "business_value": "18000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto sincronizado desde la plataforma de desarrollo (NEQ).",
      "recent_completed_examples": "NEQ-10 · Soporte upload Excel | NEQ-11 · Templates banner in-app | NEQ-12 · Motor pixel-perfect headless"
    },
    {
      "project_code": "PRJ-11",
      "engagement_type": "Proyecto",
      "client_alias": "Civica Regional",
      "project_name": "Public Service Desk",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Laura Gomez",
      "owner_role": "Delivery",
      "start_date": null,
      "target_date": "2026-05-21",
      "business_value": "15000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto sincronizado desde la plataforma de desarrollo (GOB).",
      "recent_completed_examples": "GOB-2 · Kick off | GOB-4 · Crear grupo de WA | GOB-5 · Analisis del kick off"
    },
    {
      "project_code": "PRJ-12",
      "engagement_type": "Proyecto",
      "client_alias": "Northfield Proteins",
      "project_name": "Plant Operations Automation",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Mateo Ruiz",
      "owner_role": "Delivery",
      "start_date": null,
      "target_date": "2026-05-22",
      "business_value": "9000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "1",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto sincronizado desde la plataforma de desarrollo (NTB).",
      "recent_completed_examples": "NTB-1 · Kick off | NTB-3 · Prototipo de detalle | NTB-4 · Feedback prototipo"
    },
    {
      "project_code": "PRJ-13",
      "engagement_type": "Diagnostico",
      "client_alias": "HelioGrid Energy",
      "project_name": "Commercial Automation Discovery",
      "project_type_api": "Consultoria",
      "stage": "Descubrimiento",
      "status": "Activo",
      "health": "En riesgo",
      "owner_alias": "Santiago Vera",
      "owner_role": "Delivery",
      "start_date": null,
      "target_date": "2026-05-22",
      "business_value": "12000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto sincronizado desde la plataforma de desarrollo (SVT).",
      "recent_completed_examples": "SVT-1 · NDA | SVT-4 · Repasar reunion | SVT-5 · Muestra del MVP"
    },
    {
      "project_code": "PRJ-14",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Vehicle Photography Platform",
      "project_type_api": "Automatizacion",
      "stage": "Descubrimiento",
      "status": "Activo",
      "health": "En riesgo",
      "owner_alias": "Mateo Ruiz",
      "owner_role": "Delivery",
      "start_date": "2026-04-16",
      "target_date": null,
      "business_value": "2000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Plataforma para que concesionarios tomen fotos y reciban fotos profesionales.",
      "recent_completed_examples": "Darle accesos a David"
    },
    {
      "project_code": "PRJ-15",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Legal Documents Assistant",
      "project_type_api": "Automatizacion",
      "stage": "Descubrimiento",
      "status": "Activo",
      "health": "En riesgo",
      "owner_alias": "Laura Gomez",
      "owner_role": "Delivery",
      "start_date": "2026-04-16",
      "target_date": null,
      "business_value": "1000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "1",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto creado via API.",
      "recent_completed_examples": "No completed examples visible"
    },
    {
      "project_code": "PRJ-16",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Lead Acquisition System",
      "project_type_api": "Automatizacion",
      "stage": "Descubrimiento",
      "status": "Activo",
      "health": "En riesgo",
      "owner_alias": "Mateo Ruiz",
      "owner_role": "Delivery",
      "start_date": "2026-04-16",
      "target_date": null,
      "business_value": "1000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "1",
      "blockers": "There are overdue tasks without a clear close path.",
      "summary": "Proyecto creado via API.",
      "recent_completed_examples": "Hacer kick off del proyecto"
    },
    {
      "project_code": "PRJ-17",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Billing Reconciliation Bot",
      "project_type_api": "Automatizacion",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Sano",
      "owner_alias": "Daniel Rojas",
      "owner_role": "Commercial / Delivery",
      "start_date": "2026-03-02",
      "target_date": "2026-08-28",
      "business_value": "11000",
      "currency": "USD",
      "open_tasks": "3",
      "overdue_tasks": "0",
      "blockers": null,
      "summary": "Conciliacion automatica de facturacion contra el ERP del cliente.",
      "recent_completed_examples": "AST-8 · Reglas de matcheo | AST-9 · Reporte semanal automatico"
    },
    {
      "project_code": "PRJ-18",
      "engagement_type": "Proyecto",
      "client_alias": "Andes Retail",
      "project_name": "Inventory Forecasting",
      "project_type_api": "Automatizacion",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Sano",
      "owner_alias": "Mateo Ruiz",
      "owner_role": "Delivery",
      "start_date": "2026-05-04",
      "target_date": "2026-09-12",
      "business_value": "85000000",
      "currency": "COP",
      "open_tasks": "4",
      "overdue_tasks": "0",
      "blockers": null,
      "summary": "Pronostico de inventario por punto de venta con reposicion sugerida.",
      "recent_completed_examples": "AND-3 · Modelo base | AND-7 · Integracion POS | AND-11 · Panel de reposicion"
    },
    {
      "project_code": "PRJ-19",
      "engagement_type": "Proyecto",
      "client_alias": "Meridian Legal",
      "project_name": "Contract Clause Extractor",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Sano",
      "owner_alias": "Andrea Molina",
      "owner_role": "Delivery",
      "start_date": "2026-06-01",
      "target_date": "2026-09-30",
      "business_value": "19000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "0",
      "blockers": null,
      "summary": "Extraccion de clausulas y obligaciones desde contratos en PDF.",
      "recent_completed_examples": "MER-2 · Corpus de prueba | MER-5 · Extractor v1 | MER-6 · Validacion con abogados"
    },
    {
      "project_code": "PRJ-20",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Claims Status Notifier",
      "project_type_api": "Automatizacion",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Sano",
      "owner_alias": "Laura Gomez",
      "owner_role": "Delivery",
      "start_date": "2026-04-20",
      "target_date": "2026-10-15",
      "business_value": "120000000",
      "currency": "COP",
      "open_tasks": "3",
      "overdue_tasks": "0",
      "blockers": null,
      "summary": "Notificacion automatica de estado de reclamaciones por WhatsApp.",
      "recent_completed_examples": "NOV-4 · Plantillas aprobadas | NOV-9 · Reintentos con backoff"
    },
    {
      "project_code": "PRJ-21",
      "engagement_type": "Proyecto",
      "client_alias": "Cobalt Logistics",
      "project_name": "Route Optimization Pilot",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Sano",
      "owner_alias": "Santiago Vera",
      "owner_role": "Delivery",
      "start_date": "2025-11-10",
      "target_date": "2026-02-10",
      "business_value": "16000",
      "currency": "USD",
      "open_tasks": "0",
      "overdue_tasks": "0",
      "blockers": null,
      "summary": "Piloto de optimizacion de rutas para flota regional.",
      "recent_completed_examples": "No completed examples visible"
    },
    {
      "project_code": "PRJ-22",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine (Fase 2)",
      "project_type_api": "Consultoria",
      "stage": "Ejecucion",
      "status": "Activo",
      "health": "Bloqueado",
      "owner_alias": "Camila Torres",
      "owner_role": "Delivery",
      "start_date": null,
      "target_date": "2026-04-27",
      "business_value": "38000",
      "currency": "USD",
      "open_tasks": "4",
      "overdue_tasks": "2",
      "blockers": "There are external dependencies or pending accesses. There are overdue tasks without a clear close path.",
      "summary": "Proyecto sincronizado desde la plataforma de desarrollo (QUI).",
      "recent_completed_examples": "QUI-10 · Mapa comerciales | QUI-11 · Criterios calificacion | QUI-12 · Canal WhatsApp CO"
    }
  ],
  "tasks": [
    {
      "task_code": "PRJ-01-T01",
      "project_code": "PRJ-01",
      "engagement_type": "Proyecto",
      "client_alias": "Atlas Foods",
      "project_name": "Global Contract Management",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Global Contract Management",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-01-T02",
      "project_code": "PRJ-01",
      "engagement_type": "Proyecto",
      "client_alias": "Atlas Foods",
      "project_name": "Global Contract Management",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Functional validation and release checklist",
      "title": "Resolve priority issue in pilot or production - Global Contract Management",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-01-T03",
      "project_code": "PRJ-01",
      "engagement_type": "Proyecto",
      "client_alias": "Atlas Foods",
      "project_name": "Global Contract Management",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Global Contract Management",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-01-T04",
      "project_code": "PRJ-01",
      "engagement_type": "Proyecto",
      "client_alias": "Atlas Foods",
      "project_name": "Global Contract Management",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Global Contract Management",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    },
    {
      "task_code": "PRJ-02-T01",
      "project_code": "PRJ-02",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Observability Hub",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Media",
      "status": "En progreso",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": null,
      "title": "Weekly KPI and quality monitoring - Observability Hub",
      "detail": "Weekly review of volume, response time and out-of-range events.",
      "last_progress": "Weekly review of volume, response time and out-of-range events."
    },
    {
      "task_code": "PRJ-02-T02",
      "project_code": "PRJ-02",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Observability Hub",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Alta",
      "status": "Por hacer",
      "due_date": "2026-07-11",
      "is_overdue": "Si",
      "dependency": "Weekly KPI and quality monitoring",
      "title": "Adjust the rule or automation causing most friction - Observability Hub",
      "detail": "One automation is creating manual errors or rework and needs tuning.",
      "last_progress": "One automation is creating manual errors or rework and needs tuning."
    },
    {
      "task_code": "PRJ-02-T03",
      "project_code": "PRJ-02",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Observability Hub",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Baja",
      "status": "En revision",
      "due_date": "2026-07-18",
      "is_overdue": "No",
      "dependency": "Weekly KPI and quality monitoring",
      "title": "Review historical backlog and clean stale tasks - Observability Hub",
      "detail": "Old, duplicate or unclear tasks still need cleanup.",
      "last_progress": "Old, duplicate or unclear tasks still need cleanup."
    },
    {
      "task_code": "PRJ-02-T04",
      "project_code": "PRJ-02",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Observability Hub",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Alta",
      "status": "Bloqueada",
      "due_date": "2026-07-09",
      "is_overdue": "Si",
      "dependency": "Adjust the rule or automation causing most friction",
      "title": "Unblock recurrent service dependency - Observability Hub",
      "detail": "A recurrent technical or operational dependency is hurting stability or improvements.",
      "last_progress": "A recurrent technical or operational dependency is hurting stability or improvements."
    },
    {
      "task_code": "PRJ-03-T01",
      "project_code": "PRJ-03",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Lunara Health",
      "project_name": "Patient Care Assistant",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En progreso",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": null,
      "title": "Weekly KPI and quality monitoring - Patient Care Assistant",
      "detail": "Weekly review of volume, response time and out-of-range events.",
      "last_progress": "Weekly review of volume, response time and out-of-range events."
    },
    {
      "task_code": "PRJ-03-T02",
      "project_code": "PRJ-03",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Lunara Health",
      "project_name": "Patient Care Assistant",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Por hacer",
      "due_date": "2026-07-11",
      "is_overdue": "Si",
      "dependency": "Weekly KPI and quality monitoring",
      "title": "Adjust the rule or automation causing most friction - Patient Care Assistant",
      "detail": "One automation is creating manual errors or rework and needs tuning.",
      "last_progress": "One automation is creating manual errors or rework and needs tuning."
    },
    {
      "task_code": "PRJ-03-T03",
      "project_code": "PRJ-03",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Lunara Health",
      "project_name": "Patient Care Assistant",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Baja",
      "status": "En revision",
      "due_date": "2026-07-18",
      "is_overdue": "No",
      "dependency": "Weekly KPI and quality monitoring",
      "title": "Review historical backlog and clean stale tasks - Patient Care Assistant",
      "detail": "Old, duplicate or unclear tasks still need cleanup.",
      "last_progress": "Old, duplicate or unclear tasks still need cleanup."
    },
    {
      "task_code": "PRJ-03-T04",
      "project_code": "PRJ-03",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Lunara Health",
      "project_name": "Patient Care Assistant",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Bloqueada",
      "due_date": "2026-07-09",
      "is_overdue": "Si",
      "dependency": "Adjust the rule or automation causing most friction",
      "title": "Unblock recurrent service dependency - Patient Care Assistant",
      "detail": "A recurrent technical or operational dependency is hurting stability or improvements.",
      "last_progress": "A recurrent technical or operational dependency is hurting stability or improvements."
    },
    {
      "task_code": "PRJ-04-T01",
      "project_code": "PRJ-04",
      "engagement_type": "Proyecto",
      "client_alias": "Pioneer Insurance",
      "project_name": "Quotation Engine",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Quotation Engine",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-04-T02",
      "project_code": "PRJ-04",
      "engagement_type": "Proyecto",
      "client_alias": "Pioneer Insurance",
      "project_name": "Quotation Engine",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Align external dependency with client or vendor",
      "title": "Resolve priority issue in pilot or production - Quotation Engine",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-04-T03",
      "project_code": "PRJ-04",
      "engagement_type": "Proyecto",
      "client_alias": "Pioneer Insurance",
      "project_name": "Quotation Engine",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Quotation Engine",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-04-T04",
      "project_code": "PRJ-04",
      "engagement_type": "Proyecto",
      "client_alias": "Pioneer Insurance",
      "project_name": "Quotation Engine",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Quotation Engine",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    },
    {
      "task_code": "PRJ-05-T01",
      "project_code": "PRJ-05",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Orion Mobility",
      "project_name": "Multi-Brand Sales Assistant",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En progreso",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": null,
      "title": "Weekly KPI and quality monitoring - Multi-Brand Sales Assistant",
      "detail": "Weekly review of volume, response time and out-of-range events.",
      "last_progress": "Weekly review of volume, response time and out-of-range events."
    },
    {
      "task_code": "PRJ-05-T02",
      "project_code": "PRJ-05",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Orion Mobility",
      "project_name": "Multi-Brand Sales Assistant",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Por hacer",
      "due_date": "2026-07-11",
      "is_overdue": "Si",
      "dependency": "Weekly KPI and quality monitoring",
      "title": "Adjust the rule or automation causing most friction - Multi-Brand Sales Assistant",
      "detail": "One automation is creating manual errors or rework and needs tuning.",
      "last_progress": "One automation is creating manual errors or rework and needs tuning."
    },
    {
      "task_code": "PRJ-05-T03",
      "project_code": "PRJ-05",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Orion Mobility",
      "project_name": "Multi-Brand Sales Assistant",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Baja",
      "status": "En revision",
      "due_date": "2026-07-18",
      "is_overdue": "No",
      "dependency": "Weekly KPI and quality monitoring",
      "title": "Review historical backlog and clean stale tasks - Multi-Brand Sales Assistant",
      "detail": "Old, duplicate or unclear tasks still need cleanup.",
      "last_progress": "Old, duplicate or unclear tasks still need cleanup."
    },
    {
      "task_code": "PRJ-05-T04",
      "project_code": "PRJ-05",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Orion Mobility",
      "project_name": "Multi-Brand Sales Assistant",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Bloqueada",
      "due_date": "2026-07-09",
      "is_overdue": "Si",
      "dependency": "Adjust the rule or automation causing most friction",
      "title": "Unblock recurrent service dependency - Multi-Brand Sales Assistant",
      "detail": "A recurrent technical or operational dependency is hurting stability or improvements.",
      "last_progress": "A recurrent technical or operational dependency is hurting stability or improvements."
    },
    {
      "task_code": "PRJ-06-T01",
      "project_code": "PRJ-06",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Recovery and Compensation Ops",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En progreso",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": null,
      "title": "Weekly KPI and quality monitoring - Recovery and Compensation Ops",
      "detail": "Weekly review of volume, response time and out-of-range events.",
      "last_progress": "Weekly review of volume, response time and out-of-range events."
    },
    {
      "task_code": "PRJ-06-T02",
      "project_code": "PRJ-06",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Recovery and Compensation Ops",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Por hacer",
      "due_date": "2026-07-11",
      "is_overdue": "Si",
      "dependency": "Weekly KPI and quality monitoring",
      "title": "Adjust the rule or automation causing most friction - Recovery and Compensation Ops",
      "detail": "One automation is creating manual errors or rework and needs tuning.",
      "last_progress": "One automation is creating manual errors or rework and needs tuning."
    },
    {
      "task_code": "PRJ-06-T03",
      "project_code": "PRJ-06",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Recovery and Compensation Ops",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Baja",
      "status": "En revision",
      "due_date": "2026-07-18",
      "is_overdue": "No",
      "dependency": "Weekly KPI and quality monitoring",
      "title": "Review historical backlog and clean stale tasks - Recovery and Compensation Ops",
      "detail": "Old, duplicate or unclear tasks still need cleanup.",
      "last_progress": "Old, duplicate or unclear tasks still need cleanup."
    },
    {
      "task_code": "PRJ-06-T04",
      "project_code": "PRJ-06",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Recovery and Compensation Ops",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Bloqueada",
      "due_date": "2026-07-09",
      "is_overdue": "Si",
      "dependency": "Adjust the rule or automation causing most friction",
      "title": "Unblock recurrent service dependency - Recovery and Compensation Ops",
      "detail": "A recurrent technical or operational dependency is hurting stability or improvements.",
      "last_progress": "A recurrent technical or operational dependency is hurting stability or improvements."
    },
    {
      "task_code": "PRJ-07-T01",
      "project_code": "PRJ-07",
      "engagement_type": "Proyecto",
      "client_alias": "Velora Credit",
      "project_name": "Credit Assistant",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Credit Assistant",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-07-T02",
      "project_code": "PRJ-07",
      "engagement_type": "Proyecto",
      "client_alias": "Velora Credit",
      "project_name": "Credit Assistant",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Functional validation and release checklist",
      "title": "Resolve priority issue in pilot or production - Credit Assistant",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-07-T03",
      "project_code": "PRJ-07",
      "engagement_type": "Proyecto",
      "client_alias": "Velora Credit",
      "project_name": "Credit Assistant",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Credit Assistant",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-07-T04",
      "project_code": "PRJ-07",
      "engagement_type": "Proyecto",
      "client_alias": "Velora Credit",
      "project_name": "Credit Assistant",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Credit Assistant",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    },
    {
      "task_code": "PRJ-08-T01",
      "project_code": "PRJ-08",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Messaging Qualification Engine",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-08-T02",
      "project_code": "PRJ-08",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Functional validation and release checklist",
      "title": "Resolve priority issue in pilot or production - Messaging Qualification Engine",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-08-T03",
      "project_code": "PRJ-08",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Messaging Qualification Engine",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-08-T04",
      "project_code": "PRJ-08",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Messaging Qualification Engine",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    },
    {
      "task_code": "PRJ-09-T01",
      "project_code": "PRJ-09",
      "engagement_type": "Proyecto",
      "client_alias": "Ferroline Industrial",
      "project_name": "Industrial OCR Quoter",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Industrial OCR Quoter",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-09-T02",
      "project_code": "PRJ-09",
      "engagement_type": "Proyecto",
      "client_alias": "Ferroline Industrial",
      "project_name": "Industrial OCR Quoter",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Functional validation and release checklist",
      "title": "Resolve priority issue in pilot or production - Industrial OCR Quoter",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-09-T03",
      "project_code": "PRJ-09",
      "engagement_type": "Proyecto",
      "client_alias": "Ferroline Industrial",
      "project_name": "Industrial OCR Quoter",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Industrial OCR Quoter",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-09-T04",
      "project_code": "PRJ-09",
      "engagement_type": "Proyecto",
      "client_alias": "Ferroline Industrial",
      "project_name": "Industrial OCR Quoter",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Industrial OCR Quoter",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    },
    {
      "task_code": "PRJ-10-T01",
      "project_code": "PRJ-10",
      "engagement_type": "Proyecto",
      "client_alias": "Pulse Creative",
      "project_name": "Commercial Image Pipeline",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Commercial Image Pipeline",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-10-T02",
      "project_code": "PRJ-10",
      "engagement_type": "Proyecto",
      "client_alias": "Pulse Creative",
      "project_name": "Commercial Image Pipeline",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Functional validation and release checklist",
      "title": "Resolve priority issue in pilot or production - Commercial Image Pipeline",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-10-T03",
      "project_code": "PRJ-10",
      "engagement_type": "Proyecto",
      "client_alias": "Pulse Creative",
      "project_name": "Commercial Image Pipeline",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Commercial Image Pipeline",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-10-T04",
      "project_code": "PRJ-10",
      "engagement_type": "Proyecto",
      "client_alias": "Pulse Creative",
      "project_name": "Commercial Image Pipeline",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Commercial Image Pipeline",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    },
    {
      "task_code": "PRJ-11-T01",
      "project_code": "PRJ-11",
      "engagement_type": "Proyecto",
      "client_alias": "Civica Regional",
      "project_name": "Public Service Desk",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Public Service Desk",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-11-T02",
      "project_code": "PRJ-11",
      "engagement_type": "Proyecto",
      "client_alias": "Civica Regional",
      "project_name": "Public Service Desk",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Functional validation and release checklist",
      "title": "Resolve priority issue in pilot or production - Public Service Desk",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-11-T03",
      "project_code": "PRJ-11",
      "engagement_type": "Proyecto",
      "client_alias": "Civica Regional",
      "project_name": "Public Service Desk",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Public Service Desk",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-11-T04",
      "project_code": "PRJ-11",
      "engagement_type": "Proyecto",
      "client_alias": "Civica Regional",
      "project_name": "Public Service Desk",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Public Service Desk",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    },
    {
      "task_code": "PRJ-12-T01",
      "project_code": "PRJ-12",
      "engagement_type": "Proyecto",
      "client_alias": "Northfield Proteins",
      "project_name": "Plant Operations Automation",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Plant Operations Automation",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-12-T02",
      "project_code": "PRJ-12",
      "engagement_type": "Proyecto",
      "client_alias": "Northfield Proteins",
      "project_name": "Plant Operations Automation",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Functional validation and release checklist",
      "title": "Resolve priority issue in pilot or production - Plant Operations Automation",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-12-T03",
      "project_code": "PRJ-12",
      "engagement_type": "Proyecto",
      "client_alias": "Northfield Proteins",
      "project_name": "Plant Operations Automation",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Plant Operations Automation",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-12-T04",
      "project_code": "PRJ-12",
      "engagement_type": "Proyecto",
      "client_alias": "Northfield Proteins",
      "project_name": "Plant Operations Automation",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Plant Operations Automation",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    },
    {
      "task_code": "PRJ-13-T01",
      "project_code": "PRJ-13",
      "engagement_type": "Diagnostico",
      "client_alias": "HelioGrid Energy",
      "project_name": "Commercial Automation Discovery",
      "assignee_alias": "Santiago Vera",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-11",
      "is_overdue": "No",
      "dependency": null,
      "title": "Stakeholder mapping and scope - Commercial Automation Discovery",
      "detail": "Interviews and dependency map are in progress.",
      "last_progress": "Interviews and dependency map are in progress."
    },
    {
      "task_code": "PRJ-13-T02",
      "project_code": "PRJ-13",
      "engagement_type": "Diagnostico",
      "client_alias": "HelioGrid Energy",
      "project_name": "Commercial Automation Discovery",
      "assignee_alias": "Santiago Vera",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-09",
      "is_overdue": "Si",
      "dependency": "Stakeholder mapping and scope",
      "title": "Audit current flow and breakpoints - Commercial Automation Discovery",
      "detail": "Current process timings, handoffs and failure points are still undocumented.",
      "last_progress": "Current process timings, handoffs and failure points are still undocumented."
    },
    {
      "task_code": "PRJ-13-T03",
      "project_code": "PRJ-13",
      "engagement_type": "Diagnostico",
      "client_alias": "HelioGrid Energy",
      "project_name": "Commercial Automation Discovery",
      "assignee_alias": "Santiago Vera",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En revision",
      "due_date": "2026-07-15",
      "is_overdue": "No",
      "dependency": "Audit current flow and breakpoints",
      "title": "Define solution hypotheses and quick wins - Commercial Automation Discovery",
      "detail": "First set of quick wins is drafted and waiting for validation.",
      "last_progress": "First set of quick wins is drafted and waiting for validation."
    },
    {
      "task_code": "PRJ-13-T04",
      "project_code": "PRJ-13",
      "engagement_type": "Diagnostico",
      "client_alias": "HelioGrid Energy",
      "project_name": "Commercial Automation Discovery",
      "assignee_alias": "Santiago Vera",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Bloqueada",
      "due_date": "2026-07-08",
      "is_overdue": "Si",
      "dependency": "Stakeholder mapping and scope",
      "title": "Get access to key data sources - Commercial Automation Discovery",
      "detail": "Blocked by permissions, repository access or owner confirmation.",
      "last_progress": "Blocked by permissions, repository access or owner confirmation."
    },
    {
      "task_code": "PRJ-14-T01",
      "project_code": "PRJ-14",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Vehicle Photography Platform",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-11",
      "is_overdue": "No",
      "dependency": null,
      "title": "Stakeholder mapping and scope - Vehicle Photography Platform",
      "detail": "Interviews and dependency map are in progress.",
      "last_progress": "Interviews and dependency map are in progress."
    },
    {
      "task_code": "PRJ-14-T02",
      "project_code": "PRJ-14",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Vehicle Photography Platform",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-09",
      "is_overdue": "Si",
      "dependency": "Stakeholder mapping and scope",
      "title": "Audit current flow and breakpoints - Vehicle Photography Platform",
      "detail": "Current process timings, handoffs and failure points are still undocumented.",
      "last_progress": "Current process timings, handoffs and failure points are still undocumented."
    },
    {
      "task_code": "PRJ-14-T03",
      "project_code": "PRJ-14",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Vehicle Photography Platform",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En revision",
      "due_date": "2026-07-15",
      "is_overdue": "No",
      "dependency": "Audit current flow and breakpoints",
      "title": "Define solution hypotheses and quick wins - Vehicle Photography Platform",
      "detail": "First set of quick wins is drafted and waiting for validation.",
      "last_progress": "First set of quick wins is drafted and waiting for validation."
    },
    {
      "task_code": "PRJ-14-T04",
      "project_code": "PRJ-14",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Vehicle Photography Platform",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Bloqueada",
      "due_date": "2026-07-08",
      "is_overdue": "Si",
      "dependency": "Stakeholder mapping and scope",
      "title": "Get access to key data sources - Vehicle Photography Platform",
      "detail": "Blocked by permissions, repository access or owner confirmation.",
      "last_progress": "Blocked by permissions, repository access or owner confirmation."
    },
    {
      "task_code": "PRJ-15-T01",
      "project_code": "PRJ-15",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Legal Documents Assistant",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-11",
      "is_overdue": "No",
      "dependency": null,
      "title": "Stakeholder mapping and scope - Legal Documents Assistant",
      "detail": "Interviews and dependency map are in progress.",
      "last_progress": "Interviews and dependency map are in progress."
    },
    {
      "task_code": "PRJ-15-T02",
      "project_code": "PRJ-15",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Legal Documents Assistant",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-09",
      "is_overdue": "Si",
      "dependency": "Stakeholder mapping and scope",
      "title": "Audit current flow and breakpoints - Legal Documents Assistant",
      "detail": "Current process timings, handoffs and failure points are still undocumented.",
      "last_progress": "Current process timings, handoffs and failure points are still undocumented."
    },
    {
      "task_code": "PRJ-15-T03",
      "project_code": "PRJ-15",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Legal Documents Assistant",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En revision",
      "due_date": "2026-07-15",
      "is_overdue": "No",
      "dependency": "Audit current flow and breakpoints",
      "title": "Define solution hypotheses and quick wins - Legal Documents Assistant",
      "detail": "First set of quick wins is drafted and waiting for validation.",
      "last_progress": "First set of quick wins is drafted and waiting for validation."
    },
    {
      "task_code": "PRJ-15-T04",
      "project_code": "PRJ-15",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Legal Documents Assistant",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Bloqueada",
      "due_date": "2026-07-08",
      "is_overdue": "Si",
      "dependency": "Stakeholder mapping and scope",
      "title": "Get access to key data sources - Legal Documents Assistant",
      "detail": "Blocked by permissions, repository access or owner confirmation.",
      "last_progress": "Blocked by permissions, repository access or owner confirmation."
    },
    {
      "task_code": "PRJ-16-T01",
      "project_code": "PRJ-16",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Lead Acquisition System",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-11",
      "is_overdue": "No",
      "dependency": null,
      "title": "Stakeholder mapping and scope - Lead Acquisition System",
      "detail": "Interviews and dependency map are in progress.",
      "last_progress": "Interviews and dependency map are in progress."
    },
    {
      "task_code": "PRJ-16-T02",
      "project_code": "PRJ-16",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Lead Acquisition System",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-09",
      "is_overdue": "Si",
      "dependency": "Stakeholder mapping and scope",
      "title": "Audit current flow and breakpoints - Lead Acquisition System",
      "detail": "Current process timings, handoffs and failure points are still undocumented.",
      "last_progress": "Current process timings, handoffs and failure points are still undocumented."
    },
    {
      "task_code": "PRJ-16-T03",
      "project_code": "PRJ-16",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Lead Acquisition System",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En revision",
      "due_date": "2026-07-15",
      "is_overdue": "No",
      "dependency": "Audit current flow and breakpoints",
      "title": "Define solution hypotheses and quick wins - Lead Acquisition System",
      "detail": "First set of quick wins is drafted and waiting for validation.",
      "last_progress": "First set of quick wins is drafted and waiting for validation."
    },
    {
      "task_code": "PRJ-16-T04",
      "project_code": "PRJ-16",
      "engagement_type": "Diagnostico",
      "client_alias": "Orion Mobility",
      "project_name": "Lead Acquisition System",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Bloqueada",
      "due_date": "2026-07-08",
      "is_overdue": "Si",
      "dependency": "Stakeholder mapping and scope",
      "title": "Get access to key data sources - Lead Acquisition System",
      "detail": "Blocked by permissions, repository access or owner confirmation.",
      "last_progress": "Blocked by permissions, repository access or owner confirmation."
    },
    {
      "task_code": "PRJ-17-T01",
      "project_code": "PRJ-17",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Billing Reconciliation Bot",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Media",
      "status": "En progreso",
      "due_date": "2026-08-14",
      "is_overdue": "No",
      "dependency": null,
      "title": "Iteracion en curso con entregables definidos - Billing Reconciliation Bot",
      "detail": "Scope acordado con el cliente, avance segun plan.",
      "last_progress": "Scope acordado con el cliente, avance segun plan."
    },
    {
      "task_code": "PRJ-17-T02",
      "project_code": "PRJ-17",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Billing Reconciliation Bot",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Alta",
      "status": "Por hacer",
      "due_date": "2026-08-20",
      "is_overdue": "No",
      "dependency": "Iteracion en curso con entregables definidos",
      "title": "Validacion funcional del modulo - Billing Reconciliation Bot",
      "detail": "Pendiente de arrancar cuando cierre la iteracion actual.",
      "last_progress": "Pendiente de arrancar cuando cierre la iteracion actual."
    },
    {
      "task_code": "PRJ-17-T03",
      "project_code": "PRJ-17",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Astera Ops",
      "project_name": "Billing Reconciliation Bot",
      "assignee_alias": "Daniel Rojas",
      "assignee_role": "Commercial / Delivery",
      "priority": "Baja",
      "status": "En revision",
      "due_date": "2026-08-25",
      "is_overdue": "No",
      "dependency": "Iteracion en curso con entregables definidos",
      "title": "Documentacion para operacion del cliente - Billing Reconciliation Bot",
      "detail": "Borrador listo, esperando revision del owner.",
      "last_progress": "Borrador listo, esperando revision del owner."
    },
    {
      "task_code": "PRJ-18-T01",
      "project_code": "PRJ-18",
      "engagement_type": "Proyecto",
      "client_alias": "Andes Retail",
      "project_name": "Inventory Forecasting",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En progreso",
      "due_date": "2026-08-14",
      "is_overdue": "No",
      "dependency": null,
      "title": "Iteracion en curso con entregables definidos - Inventory Forecasting",
      "detail": "Scope acordado con el cliente, avance segun plan.",
      "last_progress": "Scope acordado con el cliente, avance segun plan."
    },
    {
      "task_code": "PRJ-18-T02",
      "project_code": "PRJ-18",
      "engagement_type": "Proyecto",
      "client_alias": "Andes Retail",
      "project_name": "Inventory Forecasting",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Por hacer",
      "due_date": "2026-08-20",
      "is_overdue": "No",
      "dependency": "Iteracion en curso con entregables definidos",
      "title": "Validacion funcional del modulo - Inventory Forecasting",
      "detail": "Pendiente de arrancar cuando cierre la iteracion actual.",
      "last_progress": "Pendiente de arrancar cuando cierre la iteracion actual."
    },
    {
      "task_code": "PRJ-18-T03",
      "project_code": "PRJ-18",
      "engagement_type": "Proyecto",
      "client_alias": "Andes Retail",
      "project_name": "Inventory Forecasting",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Baja",
      "status": "En revision",
      "due_date": "2026-08-25",
      "is_overdue": "No",
      "dependency": "Iteracion en curso con entregables definidos",
      "title": "Documentacion para operacion del cliente - Inventory Forecasting",
      "detail": "Borrador listo, esperando revision del owner.",
      "last_progress": "Borrador listo, esperando revision del owner."
    },
    {
      "task_code": "PRJ-18-T04",
      "project_code": "PRJ-18",
      "engagement_type": "Proyecto",
      "client_alias": "Andes Retail",
      "project_name": "Inventory Forecasting",
      "assignee_alias": "Mateo Ruiz",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Por hacer",
      "due_date": "2026-09-02",
      "is_overdue": "No",
      "dependency": "Validacion funcional del modulo",
      "title": "Cierre de fase y handoff - Inventory Forecasting",
      "detail": "Depende del cierre de la validacion funcional.",
      "last_progress": "Depende del cierre de la validacion funcional."
    },
    {
      "task_code": "PRJ-19-T01",
      "project_code": "PRJ-19",
      "engagement_type": "Proyecto",
      "client_alias": "Meridian Legal",
      "project_name": "Contract Clause Extractor",
      "assignee_alias": "Andrea Molina",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En progreso",
      "due_date": "2026-08-14",
      "is_overdue": "No",
      "dependency": null,
      "title": "Iteracion en curso con entregables definidos - Contract Clause Extractor",
      "detail": "Scope acordado con el cliente, avance segun plan.",
      "last_progress": "Scope acordado con el cliente, avance segun plan."
    },
    {
      "task_code": "PRJ-19-T02",
      "project_code": "PRJ-19",
      "engagement_type": "Proyecto",
      "client_alias": "Meridian Legal",
      "project_name": "Contract Clause Extractor",
      "assignee_alias": "Andrea Molina",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Por hacer",
      "due_date": "2026-08-20",
      "is_overdue": "No",
      "dependency": "Iteracion en curso con entregables definidos",
      "title": "Validacion funcional del modulo - Contract Clause Extractor",
      "detail": "Pendiente de arrancar cuando cierre la iteracion actual.",
      "last_progress": "Pendiente de arrancar cuando cierre la iteracion actual."
    },
    {
      "task_code": "PRJ-19-T03",
      "project_code": "PRJ-19",
      "engagement_type": "Proyecto",
      "client_alias": "Meridian Legal",
      "project_name": "Contract Clause Extractor",
      "assignee_alias": "Andrea Molina",
      "assignee_role": "Delivery",
      "priority": "Baja",
      "status": "En revision",
      "due_date": "2026-08-25",
      "is_overdue": "No",
      "dependency": "Iteracion en curso con entregables definidos",
      "title": "Documentacion para operacion del cliente - Contract Clause Extractor",
      "detail": "Borrador listo, esperando revision del owner.",
      "last_progress": "Borrador listo, esperando revision del owner."
    },
    {
      "task_code": "PRJ-19-T04",
      "project_code": "PRJ-19",
      "engagement_type": "Proyecto",
      "client_alias": "Meridian Legal",
      "project_name": "Contract Clause Extractor",
      "assignee_alias": "Andrea Molina",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Por hacer",
      "due_date": "2026-09-02",
      "is_overdue": "No",
      "dependency": "Validacion funcional del modulo",
      "title": "Cierre de fase y handoff - Contract Clause Extractor",
      "detail": "Depende del cierre de la validacion funcional.",
      "last_progress": "Depende del cierre de la validacion funcional."
    },
    {
      "task_code": "PRJ-20-T01",
      "project_code": "PRJ-20",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Claims Status Notifier",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "En progreso",
      "due_date": "2026-08-14",
      "is_overdue": "No",
      "dependency": null,
      "title": "Iteracion en curso con entregables definidos - Claims Status Notifier",
      "detail": "Scope acordado con el cliente, avance segun plan.",
      "last_progress": "Scope acordado con el cliente, avance segun plan."
    },
    {
      "task_code": "PRJ-20-T02",
      "project_code": "PRJ-20",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Claims Status Notifier",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "Por hacer",
      "due_date": "2026-08-20",
      "is_overdue": "No",
      "dependency": "Iteracion en curso con entregables definidos",
      "title": "Validacion funcional del modulo - Claims Status Notifier",
      "detail": "Pendiente de arrancar cuando cierre la iteracion actual.",
      "last_progress": "Pendiente de arrancar cuando cierre la iteracion actual."
    },
    {
      "task_code": "PRJ-20-T03",
      "project_code": "PRJ-20",
      "engagement_type": "Mantenimiento o recurrente",
      "client_alias": "Nova Recovery",
      "project_name": "Claims Status Notifier",
      "assignee_alias": "Laura Gomez",
      "assignee_role": "Delivery",
      "priority": "Baja",
      "status": "En revision",
      "due_date": "2026-08-25",
      "is_overdue": "No",
      "dependency": "Iteracion en curso con entregables definidos",
      "title": "Documentacion para operacion del cliente - Claims Status Notifier",
      "detail": "Borrador listo, esperando revision del owner.",
      "last_progress": "Borrador listo, esperando revision del owner."
    },
    {
      "task_code": "PRJ-22-T01",
      "project_code": "PRJ-22",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine (Fase 2)",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En progreso",
      "due_date": "2026-07-12",
      "is_overdue": "Si",
      "dependency": null,
      "title": "Plan next delivery iteration - Messaging Qualification Engine (Fase 2)",
      "detail": "Next iteration is being scoped with deliverables and owners.",
      "last_progress": "Next iteration is being scoped with deliverables and owners."
    },
    {
      "task_code": "PRJ-22-T02",
      "project_code": "PRJ-22",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine (Fase 2)",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Critica",
      "status": "Por hacer",
      "due_date": "2026-07-10",
      "is_overdue": "Si",
      "dependency": "Functional validation and release checklist",
      "title": "Resolve priority issue in pilot or production - Messaging Qualification Engine (Fase 2)",
      "detail": "There is a user-visible issue affecting trust or adoption.",
      "last_progress": "There is a user-visible issue affecting trust or adoption."
    },
    {
      "task_code": "PRJ-22-T03",
      "project_code": "PRJ-22",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine (Fase 2)",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Media",
      "status": "Bloqueada",
      "due_date": "2026-07-14",
      "is_overdue": "No",
      "dependency": "Resolve priority issue in pilot or production",
      "title": "Align external dependency with client or vendor - Messaging Qualification Engine (Fase 2)",
      "detail": "Waiting on client response, credentials, external API or business definition.",
      "last_progress": "Waiting on client response, credentials, external API or business definition."
    },
    {
      "task_code": "PRJ-22-T04",
      "project_code": "PRJ-22",
      "engagement_type": "Proyecto",
      "client_alias": "Vector Partners",
      "project_name": "Messaging Qualification Engine (Fase 2)",
      "assignee_alias": "Camila Torres",
      "assignee_role": "Delivery",
      "priority": "Alta",
      "status": "En revision",
      "due_date": "2026-07-16",
      "is_overdue": "No",
      "dependency": "Plan next delivery iteration",
      "title": "Functional validation and release checklist - Messaging Qualification Engine (Fase 2)",
      "detail": "Core build exists, but edge cases still need validation before closing the front.",
      "last_progress": "Core build exists, but edge cases still need validation before closing the front."
    }
  ],
  "team": [
    {
      "member_alias": "Camila Torres",
      "role": "Delivery",
      "projects_in_portfolio": "7",
      "open_tasks_assigned": "28",
      "blocked_tasks_assigned": "7",
      "high_or_critical_open": "20",
      "diagnostico_projects": "0",
      "proyecto_projects": "6",
      "mantenimiento_projects": "1"
    },
    {
      "member_alias": "Daniel Rojas",
      "role": "Commercial / Delivery",
      "projects_in_portfolio": "3",
      "open_tasks_assigned": "11",
      "blocked_tasks_assigned": "2",
      "high_or_critical_open": "6",
      "diagnostico_projects": "0",
      "proyecto_projects": "1",
      "mantenimiento_projects": "2"
    },
    {
      "member_alias": "Laura Gomez",
      "role": "Delivery",
      "projects_in_portfolio": "5",
      "open_tasks_assigned": "19",
      "blocked_tasks_assigned": "4",
      "high_or_critical_open": "11",
      "diagnostico_projects": "1",
      "proyecto_projects": "1",
      "mantenimiento_projects": "3"
    },
    {
      "member_alias": "Mateo Ruiz",
      "role": "Delivery",
      "projects_in_portfolio": "4",
      "open_tasks_assigned": "16",
      "blocked_tasks_assigned": "3",
      "high_or_critical_open": "10",
      "diagnostico_projects": "2",
      "proyecto_projects": "2",
      "mantenimiento_projects": "0"
    },
    {
      "member_alias": "Santiago Vera",
      "role": "Delivery",
      "projects_in_portfolio": "2",
      "open_tasks_assigned": "4",
      "blocked_tasks_assigned": "1",
      "high_or_critical_open": "3",
      "diagnostico_projects": "1",
      "proyecto_projects": "1",
      "mantenimiento_projects": "0"
    },
    {
      "member_alias": "Andrea Molina",
      "role": "Delivery",
      "projects_in_portfolio": "1",
      "open_tasks_assigned": "4",
      "blocked_tasks_assigned": "0",
      "high_or_critical_open": "1",
      "diagnostico_projects": "0",
      "proyecto_projects": "1",
      "mantenimiento_projects": "0"
    }
  ]
};
